### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by stebiger** [t-ishii/auto-encoding#1]
Hi,

downloaded and installed on atom 1.0 (win8 x64) - no setting for auto encoding possible to set.

Also not opening utf-8 files correct when default encoding is set to windows 1252

**Comment by Nightbr** [comment]
Hi, Go to Packages->Auto Encoding and click on Toggle.
It will work next.
In settings, you can put UTF-8 or other encoding for new files.

Enjoy ;)

**Comment by stebiger** [comment]
Okay I did not see that toggle feature - blame me! :+1: 

seems to work now.
Last question: I do not have to toggle it every time to be active, do I?

**Comment by Nightbr** [comment]
Yep, click only once and it's okay! It works fine for me. Have a good day!

**Comment by stebiger** [comment]
Thank you :+1:

**Comment by stebiger** [comment]
I am sorry to reopen but just noticed wrong encoding.

![image](https://cloud.githubusercontent.com/assets/8200750/8873151/03651880-3204-11e5-8c82-217502ec501a.png)

File is ANSI encoded. auto-encoding Toggle is on.
Default atom encoding is windows1252

Opening UTF-8 files is  working.

**Comment by williamokano** [comment]
I'm having problems when trying to detect windows 1252 encoding.

The auto-encondigo Toggle is on and it´s saying that my file is windows 1251. Because of that I got a lot of errors on characters like:
ç , ã  á, and so on.

**Comment by t-ishii** [comment]
Show warning message when change encoding to `windows1251`.
2c90aa055

**Comment by gfviegas** [comment]
@t-ishii  What's the current version of this issue? It's not really necessary to have a warning message to make people manually change to windows1251, it just needed to correctly auto-encode.

**Comment by t-ishii** [comment]
ok. removed windows1251 message. fixed #1
