### ISSUE TITLE
Add support for selecting encoding based on extension

### ISSUE THREAD

**Issue by Sword-Smith** [t-ishii/auto-encoding#15]
I use Perl combined with mojolicious. Mojolicious stores the files in UTF8 but some of my old Perl files use Latin1. I use a lot of Scandinavian letters: æ, ø, and å. The encoding of these letters are different in UTF8 and in Latin1.

auto-encoding seems to work correctly most of the time. But! auto-encoding guesses on Windows-1252 (equivalent to Latin1 for my purposes) when I open a short Mojolicious template. All these template have the extension html.ep. If I could override the auto-encoding guess when the file has a certain extension, this should solve my problem.

I tried fixing the problem by using the package [editor-settings](https://atom.io/packages/editor-settings) but this did not fix the issue.

If I am missing an obvious solution to my problem, please let me know.

**Comment by t-ishii** [comment]
thank you issue.
added  option for using base encode. 831b7ce

**Comment by Sword-Smith** [comment]
Thank you! :+1: 

I will look at the new feature on Monday when I am back on work :)

**Comment by Sword-Smith** [comment]
This seems to have solved the problem. Thank you!
