### ISSUE TITLE
Opens file in gb2312 insted of utf-8

### ISSUE THREAD

**Issue by PawelGIX** [t-ishii/auto-encoding#6]
Example html file:
https://drive.google.com/file/d/0B96aEEzmdwXfRzB4RmwyOWN2V1k/view?usp=sharing

**Comment by t-ishii** [comment]
### now detect encode.

buffer -> gb2312

### new detect encode.

buffer -> [buffer1, buffer2, buffer3] -> [utf8, utf8, gb2312] -> utf8

ok ?

wip 612f179e56

**Comment by PawelGIX** [comment]
It seems to be fixed, but in other files sometimes I get windows1252 encoding and popup window "Change encoding to windows1252".
Why is this happening?
Example files: https://drive.google.com/file/d/0B96aEEzmdwXfZVlQYVJNWUFFZ3c/view?usp=sharing

**Comment by t-ishii** [comment]
add new option.
192e945be
divide size 1 ~ n.
decide the number of your best.

**Comment by PawelGIX** [comment]
OK thanks. This works.
